project:
  type: website
  output-dir: docs

website:
  title: "GBTD"
  sidebar:
    background: primary
    pinned: true
    align: center
    style: docked
    contents: 
      - href: index.qmd
        text: Home
      - href: readme.qmd
        text: Methodology

format:
  html:
    theme: flatly
    fontsize: 1.3em
    toc: true

execute:
  freeze: auto

